version: "3.3"
services:

  ontogpt-api:
    build: .
    ports:
    - 8000:80
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ontogpt.collaboratory.semanticscience.org
      LETSENCRYPT_HOST: ontogpt.collaboratory.semanticscience.org
    # env_file:
    #   - .env
